#!/usr/bin/env bash
# Not found page 404

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/custom_404
server {
    listen 80 default_server;
    server_name _;

    root /var/www/html;
    index index.html;

    location /redirect_me {
        rewrite ^/redirect_me https://www.youtube.com/ permanent;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }
}
EOF'

sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

sudo service nginx restart
