#!/usr/bin/env bash
# Install your load balancer
#
balancer="\
    frontend haproxy_balancer
bind *:80
mode http
default_backend webservers

backend webservers
balance roundrobin
server 350771-web-01 18.235.249.26:80 check
server 350771-web-02 34.234.201.19:80 check
"
# Upgrade and update packages
apt-get -y update
apt-get -y upgrade

# Add HAProxy PPA and update
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

# Install HAProxy
apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy restart