#!/usr/bin/env bash
# Displays Best School 9 times with an if condition

count=1

while [ $count -le 10 ]; do
    if [ $count -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((count++))
done
