#!/usr/bin/env bash
# Clock

hour=0
minute=1

for ((hour = 0; hour <= 12; hour++)); do
    for ((minute = 1; minute <= 59; minute++)); do
        printf "%02d:%02d\n" "$hour" "$minute"
    done
done | head -n 70