#!/usr/bin/env bash
# Clock

hour=0
minute=1

while [ $hour -le 12 ]; do
    minute=1
    echo "Hour: $hour"

    while [ $minute -le 59 ]; do
        echo "$minute"
        ((minute++))
    done

    ((hour++))
done